import { NextResponse } from 'next/server';
import { Section, ContentCard } from '@/types/content';

// Mock data - in production, this would come from your database
const mockSections: Section[] = [
  {
    id: 'mood-wellness',
    title: 'Mood & Wellness',
    type: 'feature',
    items: [
      {
        id: 'feature-daily-mood-checkin',
        type: 'feature',
        title: 'Daily Mood Check-In',
        subtitle: 'Complete daily mood + energy check-in with sliders, tags, and journal',
        image: 'https://via.placeholder.com/300x300/8b5cf6/ffffff?text=Daily+Mood',
        description: 'Users complete one daily mood + energy check-in with sliders, 8 tags, optional journal note, and points reward.',
        metadata: {
          priority: 'High / Q1 Polish',
          status: 'Implemented (needs UI polish + notifications)',
          effort: 'Medium',
        },
      },
      {
        id: 'feature-mood-journal',
        type: 'feature',
        title: 'Mood Journal & History',
        subtitle: 'View past check-ins with filters and personal stats',
        image: 'https://via.placeholder.com/300x300/a855f7/ffffff?text=Mood+Journal',
        description: 'View past check-ins with filters and personal stats. Week/month/year filters, stats (current/longest streak, total points, avg mood/energy), relative time display, export option.',
        metadata: {
          priority: 'High / Q1',
          status: 'Implemented (polish)',
          effort: 'Medium',
        },
      },
      {
        id: 'feature-affirmations',
        type: 'feature',
        title: 'Affirmations System',
        subtitle: 'Daily mood-based affirmations with modal display',
        image: 'https://via.placeholder.com/300x300/7c3aed/ffffff?text=Affirmations',
        description: 'Daily mood-based affirmations with modal display. Mood-filtered selection, category filter, modal component, usage tracking, opt-out toggle.',
        metadata: {
          priority: 'High / Q1',
          status: 'API ready → UI needed',
          effort: 'Medium',
        },
      },
    ],
  },
  {
    id: 'monetization-merch',
    title: 'Merch and Points Shop',
    type: 'feature',
    items: [
      {
        id: 'feature-merch-store',
        type: 'feature',
        title: 'Merch Store',
        subtitle: 'Browse and buy merch (platform-wide + per-artist stores)',
        image: 'https://via.placeholder.com/300x300/f59e0b/ffffff?text=Merch+Store',
        description: 'Browse and buy merch (platform-wide + per-artist stores). Printful/Teespring integration, artist uploads designs, public browse, login to purchase, beta artists get 100% revenue (pre-Sept 30, 2026), Stripe checkout + shipping.',
        metadata: {
          priority: 'High / Q3',
          status: 'New',
          effort: 'Medium-High',
        },
      },
      {
        id: 'feature-points-redemption',
        type: 'feature',
        title: 'Points Redemption System',
        subtitle: 'Redeem points for merch, sub discounts, or tickets',
        image: 'https://via.placeholder.com/300x300/ec4899/ffffff?text=Points+Rewards',
        description: 'Redeem points for merch, sub discounts, or tickets. Catalog page, point costs, redemption flow, inventory check (via partner API).',
        metadata: {
          priority: 'High / Q1',
          status: 'New',
          effort: 'Medium',
        },
      },
    ],
  },
  {
    id: 'communities-social',
    title: 'Communities & Social',
    type: 'feature',
    items: [
      {
        id: 'feature-moderated-comments',
        type: 'feature',
        title: 'Moderated Comments System',
        subtitle: 'Users comment on tracks with approval workflow',
        image: 'https://via.placeholder.com/300x300/06b6d4/ffffff?text=Comments',
        description: 'Users comment on tracks with approval workflow. PENDING/APPROVED/REJECTED status, admin moderation dashboard, track-specific comments.',
        metadata: {
          priority: 'Medium / Q1 Polish',
          status: 'Implemented (needs UI)',
          effort: 'Low-Medium',
        },
      },
      {
        id: 'feature-anonymous-chat',
        type: 'feature',
        title: 'Anonymous Chat Room',
        subtitle: 'Safe, anonymous community chat (LGBTQIA+ inclusive)',
        image: 'https://via.placeholder.com/300x300/14b8a6/ffffff?text=LivLive+NOW',
        description: 'Safe, anonymous community chat (LGBTQIA+ inclusive). Real-time chat, moderation tools, topic/room selection, report/block.',
        metadata: {
          priority: 'High / Q3',
          status: 'New',
          effort: 'High',
        },
      },
      {
        id: 'feature-follow-artists',
        type: 'feature',
        title: 'Follow Artists & User Profiles',
        subtitle: 'Follow artists and view public listening profiles',
        image: 'https://via.placeholder.com/300x300/22c55e/ffffff?text=Follow',
        description: 'Follow artists and view public listening profiles. Follow/unfollow button, artist profile page, public stats (streams, likes).',
        metadata: {
          priority: 'Medium / Q2',
          status: 'New',
          effort: 'Medium',
        },
      },
      {
        id: 'feature-artist-messaging',
        type: 'feature',
        title: 'Artist-to-Fan Messaging',
        subtitle: 'Basic direct messaging between artists and fans',
        image: 'https://via.placeholder.com/300x300/3b82f6/ffffff?text=Messaging',
        description: 'Basic direct messaging between artists and fans. Inbox, message history, notifications.',
        metadata: {
          priority: 'Medium / Q2',
          status: 'New',
          effort: 'High',
        },
      },
      {
        id: 'feature-playlist-sharing',
        type: 'feature',
        title: 'Playlist Sharing',
        subtitle: 'Share playlists via link (public/private)',
        image: 'https://via.placeholder.com/300x300/eab308/ffffff?text=Share',
        description: 'Share playlists via link (public/private). Generate shareable link, view-only access for non-logged-in users.',
        metadata: {
          priority: 'High / Q1',
          status: 'New',
          effort: 'Low',
        },
      },
    ],
  },
  {
    id: 'core-features',
    title: 'Core Features',
    type: 'feature',
    items: [
      {
        id: 'feature-queue-management',
        type: 'feature',
        title: 'Queue Management UI',
        subtitle: 'Drag-to-reorder queue management',
        image: 'https://via.placeholder.com/300x300/6366f1/ffffff?text=Queue',
        description: 'Drag-to-reorder queue management with intuitive UI.',
        metadata: {
          priority: 'High / Q1',
          status: 'New',
          effort: 'Medium',
        },
      },
      {
        id: 'feature-search',
        type: 'feature',
        title: 'Search Functionality',
        subtitle: 'Search tracks, artists, and playlists',
        image: 'https://via.placeholder.com/300x300/8b5cf6/ffffff?text=Search',
        description: 'Comprehensive search for tracks, artists, and playlists.',
        metadata: {
          priority: 'High / Q1',
          status: 'New',
          effort: 'Medium',
        },
      },
      {
        id: 'feature-badge-system',
        type: 'feature',
        title: 'Badge System',
        subtitle: 'Streak badges and achievements',
        image: 'https://via.placeholder.com/300x300/a855f7/ffffff?text=Badges',
        description: 'Streak badges, display system, and achievement tracking.',
        metadata: {
          priority: 'High / Q1',
          status: 'New',
          effort: 'Low-Medium',
        },
      },
      {
        id: 'feature-mood-theming',
        type: 'feature',
        title: 'Mood-Based Theming',
        subtitle: 'Dynamic colors based on mood',
        image: 'https://via.placeholder.com/300x300/7c3aed/ffffff?text=Theming',
        description: 'Dynamic color theming based on user mood settings.',
        metadata: {
          priority: 'High / Q1',
          status: 'New',
          effort: 'Medium',
        },
      },
      {
        id: 'feature-artist-payout',
        type: 'feature',
        title: 'Artist Payout Dashboard',
        subtitle: 'Monthly calculation and transparency',
        image: 'https://via.placeholder.com/300x300/f97316/ffffff?text=Payouts',
        description: 'Artist payout dashboard with monthly calculation and transparency.',
        metadata: {
          priority: 'Medium / Q2',
          status: 'Polish',
          effort: 'Low',
        },
      },
      {
        id: 'feature-livlive-pages',
        type: 'feature',
        title: 'LivLive_NOW Pages',
        subtitle: 'Interviews, testimonials, and events',
        image: 'https://via.placeholder.com/300x300/14b8a6/ffffff?text=LivLive',
        description: 'LivLive_NOW sub-brand pages for interviews, testimonials, and events.',
        metadata: {
          priority: 'High / Q3',
          status: 'New',
          effort: 'High',
        },
      },
      {
        id: 'feature-specialized-categories',
        type: 'feature',
        title: 'Specialized Music Categories',
        subtitle: 'MHz, Withdrawal, Pet, Education',
        image: 'https://via.placeholder.com/300x300/22c55e/ffffff?text=Categories',
        description: 'Specialized music categories: MHz, Withdrawal, Pet, Education.',
        metadata: {
          priority: 'High / Q3',
          status: 'New',
          effort: 'Medium',
        },
      },
      {
        id: 'feature-email-notifications',
        type: 'feature',
        title: 'Email Notifications',
        subtitle: 'Check-in reminders and streak updates',
        image: 'https://via.placeholder.com/300x300/06b6d4/ffffff?text=Email',
        description: 'Email notifications for check-in reminders, streaks, and updates.',
        metadata: {
          priority: 'High / Q1',
          status: 'New',
          effort: 'Low-Medium',
        },
      },
      {
        id: 'feature-onboarding',
        type: 'feature',
        title: 'Onboarding Flow',
        subtitle: 'Tutorials and welcome experience',
        image: 'https://via.placeholder.com/300x300/3b82f6/ffffff?text=Onboarding',
        description: 'Onboarding flow with tutorials and welcome experience.',
        metadata: {
          priority: 'High / Q1',
          status: 'New',
          effort: 'Medium',
        },
      },
    ],
  },
  {
    id: 'featured',
    title: 'Featured',
    type: 'feature',
    items: [
      {
        id: 'feature-1',
        type: 'playlist',
        title: 'Today\'s Top Hits',
        subtitle: 'The most played songs right now',
        image: 'https://via.placeholder.com/300x300/8b5cf6/ffffff?text=Top+Hits',
        metadata: { trackCount: 50 },
      },
      {
        id: 'feature-2',
        type: 'playlist',
        title: 'Discover Weekly',
        subtitle: 'Your weekly mixtape',
        image: 'https://via.placeholder.com/300x300/6366f1/ffffff?text=Discover',
        metadata: { trackCount: 30 },
      },
      {
        id: 'feature-3',
        type: 'playlist',
        title: 'Mood Mix',
        subtitle: 'Based on your mood settings',
        image: 'https://via.placeholder.com/300x300/a855f7/ffffff?text=Mood',
        metadata: { trackCount: 25 },
      },
      {
        id: 'feature-4',
        type: 'playlist',
        title: 'Chill Vibes',
        subtitle: 'Relax and unwind',
        image: 'https://via.placeholder.com/300x300/7c3aed/ffffff?text=Chill',
        metadata: { trackCount: 40 },
      },
      {
        id: 'founder-artists',
        type: 'feature',
        title: 'Founder Artists',
        subtitle: 'Early artists who helped build the platform',
        image: 'https://via.placeholder.com/300x300/8b5cf6/ffffff?text=Founder+Artists',
        description: 'Founding artists who joined during the early stages of the platform.',
        metadata: {},
      },
      {
        id: 'founder-investors',
        type: 'feature',
        title: 'Founder Investors',
        subtitle: 'Early investors supporting the platform',
        image: 'https://via.placeholder.com/300x300/a855f7/ffffff?text=Founder+Investors',
        description: 'Founding investors who supported the platform from the beginning.',
        metadata: {},
      },
      {
        id: 'founder-sponsors',
        type: 'feature',
        title: 'Founder Sponsors',
        subtitle: 'Early sponsors and partners',
        image: 'https://via.placeholder.com/300x300/7c3aed/ffffff?text=Founder+Sponsors',
        description: 'Founding sponsors and partners who helped launch the platform.',
        metadata: {},
      },
      {
        id: 'founder-listeners',
        type: 'feature',
        title: 'Founder Listeners',
        subtitle: 'Early listeners and community members',
        image: 'https://via.placeholder.com/300x300/6366f1/ffffff?text=Founder+Listeners',
        description: 'Founding listeners and community members who were there from the start.',
        metadata: {},
      },
    ],
  },
  {
    id: 'genres',
    title: 'Genres',
    type: 'genre',
    items: [
      {
        id: 'genre-hiphop-rap',
        type: 'genre',
        title: 'Hip-Hop/Rap',
        subtitle: 'The most streamed genre worldwide',
        image: 'https://via.placeholder.com/300x300/ec4899/ffffff?text=Hip-Hop%2FRap',
        items: [],
      },
      {
        id: 'genre-pop',
        type: 'genre',
        title: 'Pop',
        subtitle: 'Popular hits and chart toppers',
        image: 'https://via.placeholder.com/300x300/06b6d4/ffffff?text=Pop',
        items: [],
      },
      {
        id: 'genre-rock',
        type: 'genre',
        title: 'Rock',
        subtitle: 'Classic and modern rock',
        image: 'https://via.placeholder.com/300x300/ef4444/ffffff?text=Rock',
        items: [],
      },
      {
        id: 'genre-rnb-soul',
        type: 'genre',
        title: 'R&B/Soul',
        subtitle: 'Contemporary R&B and soul',
        image: 'https://via.placeholder.com/300x300/f97316/ffffff?text=R%26B%2FSoul',
        items: [],
      },
      {
        id: 'genre-electronic-edm',
        type: 'genre',
        title: 'Electronic/EDM',
        subtitle: 'Electronic dance music',
        image: 'https://via.placeholder.com/300x300/8b5cf6/ffffff?text=Electronic%2FEDM',
        items: [],
      },
      {
        id: 'genre-country',
        type: 'genre',
        title: 'Country',
        subtitle: 'Country music and Americana',
        image: 'https://via.placeholder.com/300x300/22c55e/ffffff?text=Country',
        items: [],
      },
      {
        id: 'genre-latin',
        type: 'genre',
        title: 'Latin',
        subtitle: 'Latin music from around the world',
        image: 'https://via.placeholder.com/300x300/eab308/ffffff?text=Latin',
        items: [],
      },
      {
        id: 'genre-kpop',
        type: 'genre',
        title: 'K-Pop',
        subtitle: 'Korean pop music',
        image: 'https://via.placeholder.com/300x300/3b82f6/ffffff?text=K-Pop',
        items: [],
      },
      {
        id: 'genre-afrobeats',
        type: 'genre',
        title: 'Afrobeats',
        subtitle: 'African beats and rhythms',
        image: 'https://via.placeholder.com/300x300/14b8a6/ffffff?text=Afrobeats',
        items: [],
      },
      {
        id: 'genre-jazz',
        type: 'genre',
        title: 'Jazz',
        subtitle: 'Smooth and classic jazz',
        image: 'https://via.placeholder.com/300x300/f59e0b/ffffff?text=Jazz',
        items: [],
      },
      {
        id: 'genre-metal',
        type: 'genre',
        title: 'Metal',
        subtitle: 'Heavy metal and subgenres',
        image: 'https://via.placeholder.com/300x300/6b7280/ffffff?text=Metal',
        items: [],
      },
      {
        id: 'genre-blues',
        type: 'genre',
        title: 'Blues',
        subtitle: 'Classic and electric blues',
        image: 'https://via.placeholder.com/300x300/1e40af/ffffff?text=Blues',
        items: [],
      },
      {
        id: 'genre-classical',
        type: 'genre',
        title: 'Classical',
        subtitle: 'Classical and orchestral music',
        image: 'https://via.placeholder.com/300x300/6366f1/ffffff?text=Classical',
        items: [],
      },
      {
        id: 'genre-folk',
        type: 'genre',
        title: 'Folk',
        subtitle: 'Traditional and indie folk',
        image: 'https://via.placeholder.com/300x300/84cc16/ffffff?text=Folk',
        items: [],
      },
      {
        id: 'genre-reggae',
        type: 'genre',
        title: 'Reggae',
        subtitle: 'Reggae, dancehall, and ska',
        image: 'https://via.placeholder.com/300x300/16a34a/ffffff?text=Reggae',
        items: [],
      },
      {
        id: 'genre-funk',
        type: 'genre',
        title: 'Funk',
        subtitle: 'Funk and groove music',
        image: 'https://via.placeholder.com/300x300/a855f7/ffffff?text=Funk',
        items: [],
      },
      {
        id: 'genre-soul',
        type: 'genre',
        title: 'Soul',
        subtitle: 'Soul music',
        image: 'https://via.placeholder.com/300x300/d97706/ffffff?text=Soul',
        items: [],
      },
      {
        id: 'genre-punk',
        type: 'genre',
        title: 'Punk',
        subtitle: 'Punk rock and hardcore',
        image: 'https://via.placeholder.com/300x300/dc2626/ffffff?text=Punk',
        items: [],
      },
      {
        id: 'genre-indie-alternative',
        type: 'genre',
        title: 'Indie/Alternative',
        subtitle: 'Indie and alternative music',
        image: 'https://via.placeholder.com/300x300/7c3aed/ffffff?text=Indie%2FAlt',
        items: [],
      },
      {
        id: 'genre-gospel-christian',
        type: 'genre',
        title: 'Gospel/Christian',
        subtitle: 'Gospel and Christian music',
        image: 'https://via.placeholder.com/300x300/059669/ffffff?text=Gospel',
        items: [],
      },
      {
        id: 'genre-world-traditional',
        type: 'genre',
        title: 'World/Traditional',
        subtitle: 'World music and traditional',
        image: 'https://via.placeholder.com/300x300/0d9488/ffffff?text=World',
        items: [],
      },
    ],
  },
  {
    id: 'artists',
    title: 'Popular Artists',
    type: 'custom',
    items: [
      {
        id: 'artist-featured-1',
        type: 'artist',
        title: 'The Weeknd',
        subtitle: 'R&B • Pop',
        image: 'https://via.placeholder.com/300x300/8b5cf6/ffffff?text=Weeknd',
      },
      {
        id: 'artist-featured-2',
        type: 'artist',
        title: 'Post Malone',
        subtitle: 'Hip Hop • Pop',
        image: 'https://via.placeholder.com/300x300/6366f1/ffffff?text=Post',
      },
      {
        id: 'artist-featured-3',
        type: 'artist',
        title: 'Dua Lipa',
        subtitle: 'Pop • Dance',
        image: 'https://via.placeholder.com/300x300/a855f7/ffffff?text=Dua',
      },
      {
        id: 'artist-featured-4',
        type: 'artist',
        title: 'Drake',
        subtitle: 'Hip Hop • R&B',
        image: 'https://via.placeholder.com/300x300/7c3aed/ffffff?text=Drake',
      },
    ],
  },
];

export async function GET() {
  // In production, fetch from database
  // For now, return mock data
  return NextResponse.json(mockSections);
}
