'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Upload,
  Music,
  Disc,
  Album,
  Image as ImageIcon,
  FileAudio,
  CheckCircle,
  AlertCircle,
  Info,
  X,
} from 'lucide-react';
import { usePlayer } from '@/store/player-store';
import { Slider } from '@/components/ui/slider';
import { Dial } from '@/components/ui/dial';

type ReleaseType = 'single' | 'ep' | 'lp' | '';

interface UploadData {
  releaseType: ReleaseType;
  tracks: Array<{
    id: string;
    file: File | null;
    title: string;
    artist: string;
    featuredArtists: string;
    genre: string;
      isrc: string;
      isrcAutoGenerated: boolean;
      explicit: boolean;
    language: string;
    copyrightYear: string;
    copyrightOwner: string;
    publisher: string;
    composer: string;
    lyricist: string;
    bpm: string;
    key: string;
    mood: {
      energy: number;
      happiness: number;
      calmness: number;
      intensity: number;
    };
    vibe: number;
  }>;
  albumArt: File | null;
  albumTitle: string;
  releaseDate: string;
  label: string;
  upc: string;
  catalogNumber: string;
  primaryGenre: string;
  secondaryGenre: string;
  mood: string;
  description: string;
}

const ACCEPTED_AUDIO_FORMATS = ['.mp3', '.wav', '.flac', '.aac', '.m4a', '.ogg', '.opus'];
const ACCEPTED_IMAGE_FORMATS = ['.jpg', '.jpeg', '.png'];
const MIN_IMAGE_SIZE = 1000; // 1000x1000 pixels minimum
const MAX_FILE_SIZE_MB = 500; // 500MB max per file
const MIN_BITRATE = 320; // 320 kbps minimum for MP3
const MIN_SAMPLE_RATE = 44100; // 44.1 kHz minimum

const RELEASE_TYPE_TRACK_COUNTS = {
  single: 1,
  ep: 2, // 2-6 tracks
  lp: 7, // 7+ tracks
};

export default function ArtistUploadPage() {
  const { sidebarWidth, isSidebarCollapsed } = usePlayer();
  const sidebarOffset = isSidebarCollapsed ? 64 : sidebarWidth;

  const [uploadData, setUploadData] = useState<UploadData>({
    releaseType: '',
    tracks: [],
    albumArt: null,
    albumTitle: '',
    releaseDate: '',
    label: '',
    upc: '',
    catalogNumber: '',
    primaryGenre: '',
    secondaryGenre: '',
    mood: '',
    description: '',
  });

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [albumArtPreview, setAlbumArtPreview] = useState<string | null>(null);
  const [trackPreviews, setTrackPreviews] = useState<Record<string, string>>({});

  const updateUploadData = (field: keyof UploadData, value: any) => {
    setUploadData((prev) => ({ ...prev, [field]: value }));
    // Clear error when field is updated
    if (errors[field]) {
      setErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[field];
        return newErrors;
      });
    }
  };

  const updateTrack = (index: number, field: string, value: any) => {
    setUploadData((prev) => {
      const newTracks = [...prev.tracks];
      newTracks[index] = { ...newTracks[index], [field]: value };
      return { ...prev, tracks: newTracks };
    });
  };

  const handleReleaseTypeSelect = (type: ReleaseType) => {
    updateUploadData('releaseType', type);
    // Initialize tracks based on release type
    const trackCount = RELEASE_TYPE_TRACK_COUNTS[type] || 1;
    const newTracks = Array.from({ length: trackCount }, (_, i) => ({
      id: `track-${i + 1}`,
      file: null,
      title: '',
      artist: '',
      featuredArtists: '',
      genre: '',
      isrc: '',
      isrcAutoGenerated: false,
      explicit: false,
      language: 'English',
      copyrightYear: new Date().getFullYear().toString(),
      copyrightOwner: '',
      publisher: '',
      composer: '',
      lyricist: '',
      bpm: '',
      key: '',
      mood: {
        energy: 50,
        happiness: 50,
        calmness: 50,
        intensity: 50,
      },
      vibe: 50,
    }));
    updateUploadData('tracks', newTracks);
  };

  const handleAudioFileUpload = (index: number, file: File | null) => {
    if (!file) return;

    // Validate file format
    const extension = '.' + file.name.split('.').pop()?.toLowerCase();
    if (!ACCEPTED_AUDIO_FORMATS.includes(extension)) {
      setErrors((prev) => ({
        ...prev,
        [`track-${index}-file`]: `Invalid format. Accepted: ${ACCEPTED_AUDIO_FORMATS.join(', ')}`,
      }));
      return;
    }

    // Validate file size
    const fileSizeMB = file.size / (1024 * 1024);
    if (fileSizeMB > MAX_FILE_SIZE_MB) {
      setErrors((prev) => ({
        ...prev,
        [`track-${index}-file`]: `File too large. Maximum: ${MAX_FILE_SIZE_MB}MB`,
      }));
      return;
    }

    updateTrack(index, 'file', file);
    setTrackPreviews((prev) => ({
      ...prev,
      [`track-${index}`]: file.name,
    }));
  };

  const handleAlbumArtUpload = (file: File | null) => {
    if (!file) return;

    // Validate image format
    const extension = '.' + file.name.split('.').pop()?.toLowerCase();
    if (!ACCEPTED_IMAGE_FORMATS.includes(extension)) {
      setErrors((prev) => ({
        ...prev,
        albumArt: `Invalid format. Accepted: ${ACCEPTED_IMAGE_FORMATS.join(', ')}`,
      }));
      return;
    }

    // Validate image dimensions
    const img = new Image();
    const objectUrl = URL.createObjectURL(file);
    img.onload = () => {
      if (img.width < MIN_IMAGE_SIZE || img.height < MIN_IMAGE_SIZE) {
        setErrors((prev) => ({
          ...prev,
          albumArt: `Image must be at least ${MIN_IMAGE_SIZE}x${MIN_IMAGE_SIZE} pixels. Current: ${img.width}x${img.height}`,
        }));
        URL.revokeObjectURL(objectUrl);
        return;
      }
      updateUploadData('albumArt', file);
      setAlbumArtPreview(objectUrl);
    };
    img.onerror = () => {
      setErrors((prev) => ({
        ...prev,
        albumArt: 'Invalid image file',
      }));
      URL.revokeObjectURL(objectUrl);
    };
    img.src = objectUrl;
  };

  const generateISRC = (countryCode: string = 'US'): string => {
    // ISRC format: CC-XXX-YY-NNNNN
    // CC = Country code (2 chars)
    // XXX = Registrant code (3 chars) - using platform code
    // YY = Year (2 digits)
    // NNNNN = Unique designation (5 digits)
    const year = new Date().getFullYear().toString().slice(-2);
    const registrantCode = 'EMP'; // EmPulse platform code
    const designation = Math.floor(Math.random() * 100000)
      .toString()
      .padStart(5, '0');
    return `${countryCode}${registrantCode}${year}${designation}`;
  };

  const handleGenerateISRC = (index: number) => {
    const newISRC = generateISRC();
    updateTrack(index, 'isrc', newISRC);
    updateTrack(index, 'isrcAutoGenerated', true);
  };

  const addTrack = () => {
    const newTrack = {
      id: `track-${uploadData.tracks.length + 1}`,
      file: null,
      title: '',
      artist: '',
      featuredArtists: '',
      genre: '',
      isrc: '',
      isrcAutoGenerated: false,
      explicit: false,
      language: 'English',
      copyrightYear: new Date().getFullYear().toString(),
      copyrightOwner: '',
      publisher: '',
      composer: '',
      lyricist: '',
      bpm: '',
      key: '',
      mood: {
        energy: 50,
        happiness: 50,
        calmness: 50,
        intensity: 50,
      },
      vibe: 50,
    };
    updateUploadData('tracks', [...uploadData.tracks, newTrack]);
  };

  const removeTrack = (index: number) => {
    const newTracks = uploadData.tracks.filter((_, i) => i !== index);
    updateUploadData('tracks', newTracks);
  };

  const handleSubmit = () => {
    // Validation
    const newErrors: Record<string, string> = {};

    if (!uploadData.releaseType) {
      newErrors.releaseType = 'Please select a release type';
    }

    if (uploadData.tracks.length === 0) {
      newErrors.tracks = 'At least one track is required';
    }

    uploadData.tracks.forEach((track, index) => {
      if (!track.file) {
        newErrors[`track-${index}-file`] = 'Audio file is required';
      }
      if (!track.title) {
        newErrors[`track-${index}-title`] = 'Track title is required';
      }
      // ISRC is optional - will be auto-generated if not provided
      if (!track.isrc) {
        // Auto-generate ISRC if not provided
        handleGenerateISRC(index);
      }
    });

    if (!uploadData.albumArt) {
      newErrors.albumArt = 'Album artwork is required';
    }

    if (!uploadData.albumTitle) {
      newErrors.albumTitle = 'Album/Release title is required';
    }

    if (!uploadData.releaseDate) {
      newErrors.releaseDate = 'Release date is required';
    }

    if (!uploadData.primaryGenre) {
      newErrors.primaryGenre = 'Primary genre is required';
    }

    setErrors(newErrors);

    if (Object.keys(newErrors).length === 0) {
      // TODO: Submit to backend
      console.log('Upload data:', uploadData);
      alert('Upload submitted! (This would connect to your backend)');
    }
  };

  return (
    <div
      className="min-h-screen p-8 pb-40 transition-all duration-200"
      style={{ marginLeft: `${sidebarOffset}px` }}
    >
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center space-y-2"
        >
          <div className="flex items-center justify-center gap-3">
            <Upload className="h-10 w-10 text-purple-400" />
            <h1 className="text-4xl font-bold text-white">Upload Your Music</h1>
          </div>
          <p className="text-gray-400">
            Upload your tracks with industry-standard quality requirements
          </p>
        </motion.div>

        {/* Quality Requirements Info */}
        <Card className="bg-blue-500/10 border-blue-500/30">
          <CardContent className="p-4">
            <div className="flex items-start gap-3">
              <Info className="h-5 w-5 text-blue-400 shrink-0 mt-0.5" />
              <div className="space-y-2 text-sm">
                <p className="text-white font-semibold">Industry Standard Requirements:</p>
                <ul className="text-gray-300 space-y-1 list-disc list-inside">
                  <li>
                    <strong>Audio Formats:</strong> MP3, WAV, FLAC, AAC, M4A, OGG, OPUS
                  </li>
                  <li>
                    <strong>Minimum Quality:</strong> 320 kbps (MP3), 44.1 kHz sample rate, 16-bit
                    minimum
                  </li>
                  <li>
                    <strong>Lossless Preferred:</strong> WAV or FLAC for best quality
                  </li>
                  <li>
                    <strong>Album Art:</strong> Minimum 1000x1000 pixels, square format (1:1 ratio),
                    JPG or PNG
                  </li>
                  <li>
                    <strong>Maximum File Size:</strong> 500MB per track
                  </li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Release Type Selection */}
        <Card className="bg-white/5 backdrop-blur-sm border-purple-500/30">
          <CardHeader>
            <CardTitle className="text-white">Release Type</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {[
                { type: 'single', label: 'Single', icon: Music, description: '1 track' },
                {
                  type: 'ep',
                  label: 'EP',
                  icon: Disc,
                  description: '2-6 tracks',
                },
                { type: 'lp', label: 'LP / Album', icon: Album, description: '7+ tracks' },
              ].map((option) => {
                const Icon = option.icon;
                return (
                  <button
                    key={option.type}
                    type="button"
                    onClick={() => handleReleaseTypeSelect(option.type as ReleaseType)}
                    className={`p-6 rounded-lg border-2 transition-all text-left ${
                      uploadData.releaseType === option.type
                        ? 'border-purple-500 bg-purple-600/20'
                        : 'border-gray-700 bg-white/5 hover:border-purple-500/50'
                    }`}
                  >
                    <Icon className="h-8 w-8 text-purple-400 mb-3" />
                    <h3 className="text-lg font-semibold text-white mb-1">{option.label}</h3>
                    <p className="text-sm text-gray-400">{option.description}</p>
                  </button>
                );
              })}
            </div>
            {errors.releaseType && (
              <p className="text-red-400 text-sm mt-2">{errors.releaseType}</p>
            )}
          </CardContent>
        </Card>

        {uploadData.releaseType && (
          <>
            {/* Album/Release Information */}
            <Card className="bg-white/5 backdrop-blur-sm border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white">Album / Release Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Album/Release Title <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="text"
                      value={uploadData.albumTitle}
                      onChange={(e) => updateUploadData('albumTitle', e.target.value)}
                      className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                      placeholder="Enter album title"
                    />
                    {errors.albumTitle && (
                      <p className="text-red-400 text-xs mt-1">{errors.albumTitle}</p>
                    )}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Release Date <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="date"
                      value={uploadData.releaseDate}
                      onChange={(e) => updateUploadData('releaseDate', e.target.value)}
                      className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                    />
                    {errors.releaseDate && (
                      <p className="text-red-400 text-xs mt-1">{errors.releaseDate}</p>
                    )}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Label (Optional)
                    </label>
                    <input
                      type="text"
                      value={uploadData.label}
                      onChange={(e) => updateUploadData('label', e.target.value)}
                      className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                      placeholder="Record label name"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      UPC / EAN (Optional)
                    </label>
                    <input
                      type="text"
                      value={uploadData.upc}
                      onChange={(e) => updateUploadData('upc', e.target.value)}
                      className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                      placeholder="Universal Product Code"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Catalog Number (Optional)
                  </label>
                  <input
                    type="text"
                    value={uploadData.catalogNumber}
                    onChange={(e) => updateUploadData('catalogNumber', e.target.value)}
                    className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                    placeholder="Label catalog number"
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Primary Genre <span className="text-red-400">*</span>
                    </label>
                    <select
                      value={uploadData.primaryGenre}
                      onChange={(e) => updateUploadData('primaryGenre', e.target.value)}
                      className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                    >
                      <option value="">Select genre</option>
                      <option value="Hip-Hop/Rap">Hip-Hop/Rap</option>
                      <option value="Pop">Pop</option>
                      <option value="Rock">Rock</option>
                      <option value="R&B/Soul">R&B/Soul</option>
                      <option value="Electronic/EDM">Electronic/EDM</option>
                      <option value="Country">Country</option>
                      <option value="Latin">Latin</option>
                      <option value="K-Pop">K-Pop</option>
                      <option value="Afrobeats">Afrobeats</option>
                      <option value="Jazz">Jazz</option>
                      <option value="Metal">Metal</option>
                      <option value="Blues">Blues</option>
                      <option value="Classical">Classical</option>
                      <option value="Folk">Folk</option>
                      <option value="Reggae">Reggae</option>
                      <option value="Funk">Funk</option>
                      <option value="Soul">Soul</option>
                      <option value="Punk">Punk</option>
                      <option value="Indie/Alternative">Indie/Alternative</option>
                      <option value="Gospel/Christian">Gospel/Christian</option>
                      <option value="World/Traditional">World/Traditional</option>
                    </select>
                    {errors.primaryGenre && (
                      <p className="text-red-400 text-xs mt-1">{errors.primaryGenre}</p>
                    )}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Secondary Genre (Optional)
                    </label>
                    <select
                      value={uploadData.secondaryGenre}
                      onChange={(e) => updateUploadData('secondaryGenre', e.target.value)}
                      className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                    >
                      <option value="">Select genre</option>
                      <option value="Hip-Hop/Rap">Hip-Hop/Rap</option>
                      <option value="Pop">Pop</option>
                      <option value="Rock">Rock</option>
                      <option value="R&B/Soul">R&B/Soul</option>
                      <option value="Electronic/EDM">Electronic/EDM</option>
                      <option value="Country">Country</option>
                      <option value="Latin">Latin</option>
                      <option value="K-Pop">K-Pop</option>
                      <option value="Afrobeats">Afrobeats</option>
                      <option value="Jazz">Jazz</option>
                      <option value="Metal">Metal</option>
                      <option value="Blues">Blues</option>
                      <option value="Classical">Classical</option>
                      <option value="Folk">Folk</option>
                      <option value="Reggae">Reggae</option>
                      <option value="Funk">Funk</option>
                      <option value="Soul">Soul</option>
                      <option value="Punk">Punk</option>
                      <option value="Indie/Alternative">Indie/Alternative</option>
                      <option value="Gospel/Christian">Gospel/Christian</option>
                      <option value="World/Traditional">World/Traditional</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">
                    Description (Optional)
                  </label>
                  <textarea
                    rows={3}
                    value={uploadData.description}
                    onChange={(e) => updateUploadData('description', e.target.value)}
                    className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500 resize-none"
                    placeholder="Album description or liner notes"
                  />
                </div>
              </CardContent>
            </Card>

            {/* Album Art Upload */}
            <Card className="bg-white/5 backdrop-blur-sm border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white">Album Artwork</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="p-4 bg-yellow-500/10 border border-yellow-500/30 rounded-lg">
                    <div className="flex items-start gap-2">
                      <AlertCircle className="h-5 w-5 text-yellow-400 shrink-0 mt-0.5" />
                      <div className="text-sm text-yellow-200">
                        <p className="font-semibold mb-1">Requirements:</p>
                        <ul className="list-disc list-inside space-y-1 text-yellow-100">
                          <li>Minimum size: 1000x1000 pixels (square format)</li>
                          <li>Formats: JPG, JPEG, or PNG</li>
                          <li>Recommended: 3000x3000 pixels for best quality</li>
                          <li>File size: Maximum 10MB</li>
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-6">
                    <div>
                      <input
                        type="file"
                        accept="image/jpeg,image/jpg,image/png"
                        onChange={(e) => handleAlbumArtUpload(e.target.files?.[0] || null)}
                        className="hidden"
                        id="albumArt"
                      />
                      <label
                        htmlFor="albumArt"
                        className="px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white rounded-lg cursor-pointer flex items-center gap-2"
                      >
                        <ImageIcon className="h-5 w-5" />
                        Upload Album Art
                      </label>
                    </div>
                    {albumArtPreview && (
                      <div className="relative">
                        <img
                          src={albumArtPreview}
                          alt="Album art preview"
                          className="w-32 h-32 rounded-lg object-cover border-2 border-purple-500/50"
                        />
                        <button
                          type="button"
                          onClick={() => {
                            updateUploadData('albumArt', null);
                            setAlbumArtPreview(null);
                            URL.revokeObjectURL(albumArtPreview);
                          }}
                          className="absolute -top-2 -right-2 w-6 h-6 bg-red-500 rounded-full flex items-center justify-center hover:bg-red-600"
                        >
                          <X className="h-4 w-4 text-white" />
                        </button>
                      </div>
                    )}
                  </div>
                  {errors.albumArt && (
                    <p className="text-red-400 text-sm">{errors.albumArt}</p>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Tracks */}
            <Card className="bg-white/5 backdrop-blur-sm border-purple-500/30">
              <CardHeader className="flex flex-row items-center justify-between">
                <CardTitle className="text-white">Tracks</CardTitle>
                {uploadData.releaseType !== 'single' && (
                  <Button
                    variant="outline"
                    onClick={addTrack}
                    className="border-purple-500/30 text-white hover:bg-white/10"
                  >
                    <Music className="h-4 w-4 mr-2" />
                    Add Track
                  </Button>
                )}
              </CardHeader>
              <CardContent className="space-y-6">
                {uploadData.tracks.map((track, index) => (
                  <div
                    key={track.id}
                    className="p-6 bg-white/5 rounded-lg border border-purple-500/20 space-y-4"
                  >
                    <div className="flex items-center justify-between mb-4">
                      <h3 className="text-lg font-semibold text-white">
                        Track {index + 1}
                        {uploadData.releaseType !== 'single' && (
                          <span className="text-sm font-normal text-gray-400 ml-2">
                            ({uploadData.tracks.length} total)
                          </span>
                        )}
                      </h3>
                      {uploadData.releaseType !== 'single' && uploadData.tracks.length > 1 && (
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => removeTrack(index)}
                          className="text-red-400 hover:text-red-300 hover:bg-red-500/10"
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      )}
                    </div>

                    <Tabs defaultValue="basic" className="space-y-4">
                      <TabsList className="bg-white/5 border-purple-500/30">
                        <TabsTrigger
                          value="basic"
                          className="data-[state=active]:bg-purple-600/30"
                        >
                          Basic Info
                        </TabsTrigger>
                        <TabsTrigger
                          value="metadata"
                          className="data-[state=active]:bg-purple-600/30"
                        >
                          Metadata
                        </TabsTrigger>
                        <TabsTrigger
                          value="copyright"
                          className="data-[state=active]:bg-purple-600/30"
                        >
                          Copyright
                        </TabsTrigger>
                      </TabsList>

                      <TabsContent value="basic" className="space-y-4">
                        {/* Mood & Vibe Settings - FIRST SECTION */}
                        <div className="p-6 bg-gradient-to-r from-purple-500/20 to-pink-500/20 border-2 border-purple-500/50 rounded-lg space-y-4">
                          <div className="flex items-start gap-3 mb-4">
                            <Info className="h-6 w-6 text-purple-400 shrink-0 mt-0.5" />
                            <div>
                              <h3 className="text-lg font-bold text-white mb-2">
                                Set Track Mood & Vibe
                              </h3>
                              <p className="text-sm text-purple-200 mb-1">
                                <strong className="text-white">Important:</strong> The more
                                accurate your mood settings, the better your track will be matched
                                with the right audience. Our algorithm uses these settings to
                                recommend your music to listeners with matching mood preferences.
                              </p>
                              <p className="text-xs text-purple-300">
                                Accurate mood settings = More plays from your target audience
                              </p>
                            </div>
                          </div>

                          {/* Mood Sliders */}
                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                            <div className="space-y-2">
                              <label className="text-sm font-medium text-white">
                                Energy: {track.mood.energy}
                              </label>
                              <Slider
                                value={[track.mood.energy]}
                                onValueChange={([v]) =>
                                  updateTrack(index, 'mood', {
                                    ...track.mood,
                                    energy: v,
                                  })
                                }
                                max={100}
                                step={1}
                                className="w-full"
                              />
                            </div>

                            <div className="space-y-2">
                              <label className="text-sm font-medium text-white">
                                Happiness: {track.mood.happiness}
                              </label>
                              <Slider
                                value={[track.mood.happiness]}
                                onValueChange={([v]) =>
                                  updateTrack(index, 'mood', {
                                    ...track.mood,
                                    happiness: v,
                                  })
                                }
                                max={100}
                                step={1}
                                className="w-full"
                              />
                            </div>

                            <div className="space-y-2">
                              <label className="text-sm font-medium text-white">
                                Calmness: {track.mood.calmness}
                              </label>
                              <Slider
                                value={[track.mood.calmness]}
                                onValueChange={([v]) =>
                                  updateTrack(index, 'mood', {
                                    ...track.mood,
                                    calmness: v,
                                  })
                                }
                                max={100}
                                step={1}
                                className="w-full"
                              />
                            </div>

                            <div className="space-y-2">
                              <label className="text-sm font-medium text-white">
                                Intensity: {track.mood.intensity}
                              </label>
                              <Slider
                                value={[track.mood.intensity]}
                                onValueChange={([v]) =>
                                  updateTrack(index, 'mood', {
                                    ...track.mood,
                                    intensity: v,
                                  })
                                }
                                max={100}
                                step={1}
                                className="w-full"
                              />
                            </div>
                          </div>

                          {/* Vibe Dial */}
                          <div className="flex items-center justify-center pt-4 border-t border-purple-500/30">
                            <Dial
                              value={track.vibe}
                              onChange={(v) => updateTrack(index, 'vibe', v)}
                              min={0}
                              max={100}
                              size={120}
                              label="Overall Vibe"
                            />
                          </div>
                        </div>

                        {/* Audio File Upload */}
                        <div>
                          <label className="block text-sm font-medium text-gray-300 mb-2">
                            Audio File <span className="text-red-400">*</span>
                          </label>
                          <div className="space-y-2">
                            <input
                              type="file"
                              accept={ACCEPTED_AUDIO_FORMATS.join(',')}
                              onChange={(e) =>
                                handleAudioFileUpload(index, e.target.files?.[0] || null)
                              }
                              className="hidden"
                              id={`track-${index}-file`}
                            />
                            <label
                              htmlFor={`track-${index}-file`}
                              className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg cursor-pointer inline-flex items-center gap-2"
                            >
                              <FileAudio className="h-4 w-4" />
                              {track.file ? 'Change File' : 'Select Audio File'}
                            </label>
                            {trackPreviews[`track-${index}`] && (
                              <div className="flex items-center gap-2 p-2 bg-green-500/10 border border-green-500/30 rounded">
                                <CheckCircle className="h-4 w-4 text-green-400" />
                                <span className="text-sm text-green-300">
                                  {trackPreviews[`track-${index}`]}
                                </span>
                              </div>
                            )}
                            {errors[`track-${index}-file`] && (
                              <p className="text-red-400 text-sm">
                                {errors[`track-${index}-file`]}
                              </p>
                            )}
                          </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Track Title <span className="text-red-400">*</span>
                            </label>
                            <input
                              type="text"
                              value={track.title}
                              onChange={(e) => updateTrack(index, 'title', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                              placeholder="Enter track title"
                            />
                            {errors[`track-${index}-title`] && (
                              <p className="text-red-400 text-xs mt-1">
                                {errors[`track-${index}-title`]}
                              </p>
                            )}
                          </div>
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Primary Artist <span className="text-red-400">*</span>
                            </label>
                            <input
                              type="text"
                              value={track.artist}
                              onChange={(e) => updateTrack(index, 'artist', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                              placeholder="Artist name"
                            />
                          </div>
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-gray-300 mb-2">
                            Featured Artists (Optional)
                          </label>
                          <input
                            type="text"
                            value={track.featuredArtists}
                            onChange={(e) => updateTrack(index, 'featuredArtists', e.target.value)}
                            className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                            placeholder="Separate multiple artists with commas"
                          />
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Genre
                            </label>
                            <select
                              value={track.genre}
                              onChange={(e) => updateTrack(index, 'genre', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                            >
                              <option value="">Select genre</option>
                              <option value="Hip-Hop/Rap">Hip-Hop/Rap</option>
                              <option value="Pop">Pop</option>
                              <option value="Rock">Rock</option>
                              <option value="R&B/Soul">R&B/Soul</option>
                              <option value="Electronic/EDM">Electronic/EDM</option>
                              <option value="Country">Country</option>
                              <option value="Latin">Latin</option>
                              <option value="K-Pop">K-Pop</option>
                              <option value="Afrobeats">Afrobeats</option>
                              <option value="Jazz">Jazz</option>
                              <option value="Metal">Metal</option>
                              <option value="Blues">Blues</option>
                              <option value="Classical">Classical</option>
                              <option value="Folk">Folk</option>
                              <option value="Reggae">Reggae</option>
                              <option value="Funk">Funk</option>
                              <option value="Soul">Soul</option>
                              <option value="Punk">Punk</option>
                              <option value="Indie/Alternative">Indie/Alternative</option>
                              <option value="Gospel/Christian">Gospel/Christian</option>
                              <option value="World/Traditional">World/Traditional</option>
                            </select>
                          </div>
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              ISRC Code
                              {track.isrcAutoGenerated && (
                                <Badge variant="secondary" className="ml-2 bg-green-600/30 text-green-300 text-xs">
                                  Auto-Generated
                                </Badge>
                              )}
                            </label>
                            <div className="flex gap-2">
                              <input
                                type="text"
                                value={track.isrc}
                                onChange={(e) => {
                                  updateTrack(index, 'isrc', e.target.value);
                                  if (e.target.value) {
                                    updateTrack(index, 'isrcAutoGenerated', false);
                                  }
                                }}
                                className="flex-1 px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500 disabled:opacity-50 disabled:cursor-not-allowed"
                                placeholder="USEMP24012345"
                                maxLength={12}
                                disabled={track.isrcAutoGenerated}
                              />
                              {!track.isrc && (
                                <Button
                                  type="button"
                                  variant="outline"
                                  onClick={() => handleGenerateISRC(index)}
                                  className="border-purple-500/30 bg-white/5 text-white hover:bg-white/10 hover:text-white whitespace-nowrap"
                                >
                                  Generate ISRC
                                </Button>
                              )}
                            </div>
                            <p className="text-xs text-gray-500 mt-1">
                              {track.isrcAutoGenerated
                                ? 'ISRC code will be auto-generated if not provided'
                                : '12-character ISRC code (optional - we can generate one for you)'}
                            </p>
                            {errors[`track-${index}-isrc`] && (
                              <p className="text-red-400 text-xs mt-1">
                                {errors[`track-${index}-isrc`]}
                              </p>
                            )}
                          </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Language
                            </label>
                            <select
                              value={track.language}
                              onChange={(e) => updateTrack(index, 'language', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                            >
                              <option value="English">English</option>
                              <option value="Spanish">Spanish</option>
                              <option value="French">French</option>
                              <option value="German">German</option>
                              <option value="Italian">Italian</option>
                              <option value="Portuguese">Portuguese</option>
                              <option value="Japanese">Japanese</option>
                              <option value="Korean">Korean</option>
                              <option value="Chinese">Chinese</option>
                              <option value="Other">Other</option>
                            </select>
                          </div>
                          <div className="flex items-center gap-2 pt-8">
                            <input
                              type="checkbox"
                              id={`track-${index}-explicit`}
                              checked={track.explicit}
                              onChange={(e) => updateTrack(index, 'explicit', e.target.checked)}
                              className="w-5 h-5"
                            />
                            <label
                              htmlFor={`track-${index}-explicit`}
                              className="text-sm text-white cursor-pointer"
                            >
                              Explicit Content
                            </label>
                          </div>
                        </div>
                      </TabsContent>

                      <TabsContent value="metadata" className="space-y-4">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              BPM (Beats Per Minute)
                            </label>
                            <input
                              type="number"
                              value={track.bpm}
                              onChange={(e) => updateTrack(index, 'bpm', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                              placeholder="120"
                            />
                          </div>
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Key
                            </label>
                            <select
                              value={track.key}
                              onChange={(e) => updateTrack(index, 'key', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                            >
                              <option value="">Select key</option>
                              <option value="C">C</option>
                              <option value="C#">C#</option>
                              <option value="D">D</option>
                              <option value="D#">D#</option>
                              <option value="E">E</option>
                              <option value="F">F</option>
                              <option value="F#">F#</option>
                              <option value="G">G</option>
                              <option value="G#">G#</option>
                              <option value="A">A</option>
                              <option value="A#">A#</option>
                              <option value="B">B</option>
                            </select>
                          </div>
                        </div>
                      </TabsContent>

                      <TabsContent value="copyright" className="space-y-4">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Copyright Year
                            </label>
                            <input
                              type="text"
                              value={track.copyrightYear}
                              onChange={(e) => updateTrack(index, 'copyrightYear', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                              placeholder="2024"
                            />
                          </div>
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Copyright Owner
                            </label>
                            <input
                              type="text"
                              value={track.copyrightOwner}
                              onChange={(e) => updateTrack(index, 'copyrightOwner', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                              placeholder="Copyright holder name"
                            />
                          </div>
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-gray-300 mb-2">
                            Publisher
                          </label>
                          <input
                            type="text"
                            value={track.publisher}
                            onChange={(e) => updateTrack(index, 'publisher', e.target.value)}
                            className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                            placeholder="Publisher name"
                          />
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Composer
                            </label>
                            <input
                              type="text"
                              value={track.composer}
                              onChange={(e) => updateTrack(index, 'composer', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                              placeholder="Composer name"
                            />
                          </div>
                          <div>
                            <label className="block text-sm font-medium text-gray-300 mb-2">
                              Lyricist
                            </label>
                            <input
                              type="text"
                              value={track.lyricist}
                              onChange={(e) => updateTrack(index, 'lyricist', e.target.value)}
                              className="w-full px-4 py-2 bg-white/5 border border-purple-500/30 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                              placeholder="Lyricist name"
                            />
                          </div>
                        </div>
                      </TabsContent>
                    </Tabs>
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* Submit Button */}
            <div className="flex justify-end gap-4">
              <Button
                type="button"
                variant="outline"
                className="border-purple-500/30 bg-white/5 text-white hover:bg-white/10 hover:text-white"
                onClick={() => {
                  // TODO: Save as draft
                  console.log('Save draft:', uploadData);
                  alert('Draft saved! (This would connect to your backend)');
                }}
              >
                Save as Draft
              </Button>
              <Button
                type="button"
                onClick={handleSubmit}
                className="bg-purple-600 hover:bg-purple-700 text-white px-8"
              >
                <Upload className="h-4 w-4 mr-2" />
                Upload Release
              </Button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
